version: "3"
services:
  app:
    build: ./
    container_name: PerfectFashionBlogApi-app
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/blogpostdemo4
      SPRING_DATASOURCE_PASSWORD: DivineMercy123
      SPRING_DATASOURCE_USERNAME: root
    depends_on:
      - db
    networks:
      - fashion-api

  db:
    image: mysql:latest
    container_name: mysqlDB
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: DivineMercy123
      MYSQL_DATABASE: blogpostdemo4
      MYSQL_USER: admin
      MYSQL_PASSWORD: DivineMercy123
    networks:
      - fashion-api

networks:
  fashion-api:
    driver: bridge
